# === Anti-Echo Chamber Improved Config (v5: Better Classification) ===
version: 5

# === Hugging Face dataset for artifact storage ===
hf_dataset_id: "zanimal/anti-echo-artifacts"

# === Local Chroma collections ===
chroma_collections:
  topic: "news_topic"
  stance: "news_stance"

# === Embedding models ===
embeddings:
  topic_model: "intfloat/e5-base-v2"                 # strong topic model (dense retrieval)
  stance_model: "Snowflake/snowflake-arctic-embed-l" # ideology-aware stance encoder
  dim: 1024                                          # stance embedding dimensionality
  dtype: "float16"                                   # efficient precision for Chroma
  pooling: "mean"
  chunk_tokens: 512
  normalize: true

# === Topic inference ===
topics:
  source: "https://raw.githubusercontent.com/AHMerrill/anti-echo-chamber/main/config/topics.json"
  max_topics_per_article: 5
  similarity_threshold: 0.3  # Lowered from 0.4 for better matching

# === Improved Stance Classification ===
stance_processing:
  mode: "improved-classification"
  variants: ["label", "summary"]

  # --- Stage 1: Improved Ideological Classification ---
  classifier:
    model: "google/flan-t5-large"
    max_tokens: 1024
    truncation: 1500  # Reduced for better focus
    temperature: 0.1  # Lower temperature for more consistent outputs
    do_sample: false  # Deterministic generation
    num_beams: 4
    early_stopping: true
    prompt_style: "structured"
    description: >
      Uses structured prompting with clear examples and validation
      to improve classification accuracy and reduce "unknown" results

  # --- Stage 2: Rhetorical summarization (BART) ---
  summarizer:
    model: "facebook/bart-large-cnn"
    target_sentences: 1
    max_input_chars: 3000
    do_sample: false
    description: >
      Produces one concise, natural-sounding sentence summarizing the article's
      argument, tone, or worldview without explicit labeling.

  # --- Stage 3: Hybrid embedding configuration ---
  hybrid_embedding:
    concatenate_order: ["political_leaning", "implied_stance", "summary"]
    max_length_chars: 4096
    description: >
      Concatenates ideological classification and single-sentence summary into
      one text block for stance embeddings.

# === Batch artifact management ===
batch:
  base_dir: "batches"
  manifest_name: "manifest.json"
  topic_file: "embeddings_topic.npz"
  stance_file: "embeddings_stance.npz"
  metadata_file: "metadata.jsonl"
  compress: true
  dtype: "float16"
  hf_push: true

# === Identifier and hashing scheme ===
ids:
  scheme: "domain-slug-sha12"
  hash: "sha256"
  normalize_whitespace: true
  lowercase: true
  include_timestamp: true

# === Chroma persistence and similarity metric ===
chroma:
  dir: "chroma_db"
  distance_metric: "cosine"
  rebuild_if_missing: true

# === Logging, diagnostics, and recovery ===
logging:
  level: "INFO"
  save_dir: "logs"
  record_failures: true
  checkpoint_interval: 100

# === Diagnostics and validation ===
diagnostics:
  validate_embeddings: true
  sample_summary_preview: true
  max_preview_chars: 500
  verify_stance_variants: true
  check_json_integrity: true
  verify_dual_model: true
  test_classification_quality: true  # New: test classification on sample texts
